name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Nathan Reis"
          git config --global user.email "nathanlemos.ec@gmail.com"

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run deploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GHA_TOKEN }}
          publish_dir: ./dist
          publish_branch: build
